; ====================================================================
; RETROBAT GAME MODE OPTIMIZER CONFIGURATION FILE
; ====================================================================

[Settings]
EnableOptimization=true
KillExplorer=true
EmptyWorkingSet=true
SuspendBackgroundApps=true
HideNonSuspendedWindows=true
ShowOverlay=true
Language=system
AutoStartWithRetroBat=true
ShowConsole=false
LogToFile=true
Whitelist=retrobat, emulationstation, retroarch, vlc
HideWhitelist=retrobat, emulationstation, retroarch, vlc, explorer
SuspendedApps=
LastSuspendedApps=
HiddenApps=
LastHiddenApps=
